const teachers = [
  {
    id: 1,
    name: "Seldon",
    ingredients: "phisics",
    location: "Haifa",
    price: "50 🤑",
    photoName: "images/Sheldon.jpg",
    soldOut: false,
    contact: "0546457645",
  },
  {
    id: 2,
    name: "Leonard",
    ingredients: "Phisics",
    location: "Tel Aviv",
    price: "10 🤑",
    photoName: "images/leonard.jpg",
    soldOut: false,
    contact: "0575748745",
  },
  {
    id: 3,
    name: "Penny",
    ingredients: "theatre",
    location: "Jerusalem",
    price: "41 🤑",
    photoName: "images/penny.jpg",
    soldOut: false,
  },
  {
    id: 4,
    name: "Amy",
    ingredients: "Biology",
    location: "Netanya",
    price: "90 🤑",
    photoName: "images/amy.jpg",
    soldOut: false,
    contact: "1111111111",
  },
  {
    id: 5,
    name: "Howard",
    ingredients: "computer science",
    location: "Haifa",
    price: "14 🤑",
    photoName: "images/howard.jpg",
    soldOut: true,
    contact: "68765975543",
  },
  {
    id: 6,
    name: "Rajesh",
    ingredients: "Math",
    location: "Tel Aviv",
    price: "18 🤑",
    photoName: "images/rajesh.jpg",
    soldOut: false,
    contact: "687659567653",
  },
];

module.exports = teachers;